"""Canonical Research Evidence layer."""

from .control_plane import (
    RESEARCH_CLAIM_COLLECTION,
    RESEARCH_COLLECTIONS,
    RESEARCH_COMMANDS,
    RESEARCH_EVIDENCE_COLLECTION,
    RESEARCH_ITEM_COLLECTION,
    RESEARCH_OBSERVATION_COLLECTION,
    RESEARCH_SOURCE_COLLECTION,
    ResearchClaimResourceService,
    ResearchEvidenceResourceService,
    ResearchItemResourceService,
    ResearchObservationResourceService,
    ResearchSourceResourceService,
    register_research_control_plane,
)
from .decision import ResearchDecisionBridge, ResearchDecisionReferences
from .integrations import ResearchPlanningBridge, ResearchPromotionBridge
from .models import (
    Claim,
    ClaimConfidence,
    ClaimStatus,
    EvidenceFreshness,
    EvidenceRecord,
    EvidenceRelation,
    FreshnessPolicy,
    ResearchActionContext,
    ResearchClass,
    ResearchItem,
    ResearchSourceType,
    ResearchStatus,
    ResearchVerificationBinding,
    ResearchVerificationSubjectType,
    SourceObservation,
    SourceObservationState,
    SourceRecord,
    UntrustedResearchExecutionProfile,
)
from .repository import (
    RESEARCH_PERSISTENCE_SCHEMA_VERSION,
    InMemoryResearchRepository,
    ResearchRepository,
    SqliteResearchRepository,
)
from .service import ResearchService
from .verification import ResearchVerificationBridge, ResearchVerificationSubject

__all__ = [
    "RESEARCH_CLAIM_COLLECTION",
    "RESEARCH_COLLECTIONS",
    "RESEARCH_COMMANDS",
    "RESEARCH_EVIDENCE_COLLECTION",
    "RESEARCH_ITEM_COLLECTION",
    "RESEARCH_OBSERVATION_COLLECTION",
    "RESEARCH_PERSISTENCE_SCHEMA_VERSION",
    "RESEARCH_SOURCE_COLLECTION",
    "Claim",
    "ClaimConfidence",
    "ClaimStatus",
    "EvidenceFreshness",
    "EvidenceRecord",
    "EvidenceRelation",
    "FreshnessPolicy",
    "InMemoryResearchRepository",
    "ResearchActionContext",
    "ResearchClaimResourceService",
    "ResearchClass",
    "ResearchDecisionBridge",
    "ResearchDecisionReferences",
    "ResearchEvidenceResourceService",
    "ResearchItem",
    "ResearchItemResourceService",
    "ResearchObservationResourceService",
    "ResearchPlanningBridge",
    "ResearchPromotionBridge",
    "ResearchRepository",
    "ResearchService",
    "ResearchSourceResourceService",
    "ResearchSourceType",
    "ResearchStatus",
    "ResearchVerificationBinding",
    "ResearchVerificationBridge",
    "ResearchVerificationSubject",
    "ResearchVerificationSubjectType",
    "SourceObservation",
    "SourceObservationState",
    "SourceRecord",
    "SqliteResearchRepository",
    "UntrustedResearchExecutionProfile",
    "register_research_control_plane",
]
