"""Versioned plugin SDK and lifecycle foundation."""

from .binders import CapabilityRegistryBinder
from .control_plane import (
    PLUGIN_CANDIDATE_COLLECTION,
    PLUGIN_COLLECTION,
    PLUGIN_COMMANDS,
    PLUGIN_CONFIGURE_COMMAND,
    PLUGIN_DISABLE_COMMAND,
    PLUGIN_DISCOVER_COMMAND,
    PLUGIN_ENABLE_COMMAND,
    PLUGIN_INSTALL_COMMAND,
    PLUGIN_REFRESH_HEALTH_COMMAND,
    PLUGIN_REMOVE_COMMAND,
    PLUGIN_VALIDATE_UPDATE_COMMAND,
    PluginCandidateResourceService,
    PluginLifecycleCommands,
    PluginPermissionGrantResolver,
    PluginResourceService,
    plugin_command_handlers,
    plugin_resource_services,
)
from .discovery import (
    DiscoveredPlugin,
    PluginCatalog,
    PluginRuntimeFactory,
    PluginSource,
    StaticPluginSource,
)
from .manifest import PLUGIN_MANIFEST_SCHEMA, validate_manifest_document
from .models import (
    CompatibilityState,
    ExtensionType,
    PluginDependency,
    PluginExtensionSpec,
    PluginHealth,
    PluginHealthReport,
    PluginManifest,
    PluginPermission,
    PluginProvenance,
    PluginSnapshot,
    PluginState,
    PluginStateMigrationSpec,
    VersionRange,
)
from .reference import ReferenceCapabilityPlugin, reference_manifest
from .registry import PluginRegistry
from .runtime import ExtensionBinder, ExtensionRegistration, PluginContext, PluginRuntime
from .state import (
    InMemoryPluginStateStore,
    PluginOwnedState,
    PluginStateMigration,
    PluginStateMigrator,
    PluginStateStore,
)

__all__ = [
    "PLUGIN_CANDIDATE_COLLECTION",
    "PLUGIN_COLLECTION",
    "PLUGIN_COMMANDS",
    "PLUGIN_CONFIGURE_COMMAND",
    "PLUGIN_DISABLE_COMMAND",
    "PLUGIN_DISCOVER_COMMAND",
    "PLUGIN_ENABLE_COMMAND",
    "PLUGIN_INSTALL_COMMAND",
    "PLUGIN_MANIFEST_SCHEMA",
    "PLUGIN_REFRESH_HEALTH_COMMAND",
    "PLUGIN_REMOVE_COMMAND",
    "PLUGIN_VALIDATE_UPDATE_COMMAND",
    "CapabilityRegistryBinder",
    "CompatibilityState",
    "DiscoveredPlugin",
    "ExtensionBinder",
    "ExtensionRegistration",
    "ExtensionType",
    "InMemoryPluginStateStore",
    "PluginCandidateResourceService",
    "PluginCatalog",
    "PluginContext",
    "PluginDependency",
    "PluginExtensionSpec",
    "PluginHealth",
    "PluginHealthReport",
    "PluginLifecycleCommands",
    "PluginManifest",
    "PluginOwnedState",
    "PluginPermission",
    "PluginPermissionGrantResolver",
    "PluginProvenance",
    "PluginRegistry",
    "PluginResourceService",
    "PluginRuntime",
    "PluginRuntimeFactory",
    "PluginSnapshot",
    "PluginSource",
    "PluginState",
    "PluginStateMigration",
    "PluginStateMigrationSpec",
    "PluginStateMigrator",
    "PluginStateStore",
    "ReferenceCapabilityPlugin",
    "StaticPluginSource",
    "VersionRange",
    "plugin_command_handlers",
    "plugin_resource_services",
    "reference_manifest",
    "validate_manifest_document",
]
