"""Portable canonical import/export contracts for issue #79."""

from .agent_codecs import (
    AGENT_PORTABLE_SCHEMA_VERSION,
    AGENT_RESOURCE_TYPE,
    AGENT_TEAM_RESOURCE_TYPE,
    AgentPortableCodec,
    AgentPortableSnapshot,
    AgentTeamPortableCodec,
    AgentTeamPortableSnapshot,
    register_agent_portability_codecs,
    snapshot_agent,
    snapshot_agent_team,
)
from .agent_import import AgentImportMutationHandler, AgentTeamImportMutationHandler
from .automation_codecs import (
    AUTOMATION_PORTABLE_SCHEMA_VERSION,
    AUTOMATION_RESOURCE_TYPE,
    AutomationPortableCodec,
    AutomationPortableSnapshot,
    automation_runtime_exclusions,
    register_automation_portability_codec,
    snapshot_automation,
)
from .automation_import import AutomationImportMutationHandler, AutomationImportPolicy
from .connector_codecs import (
    CONNECTION_PORTABLE_SCHEMA_VERSION,
    CONNECTION_RESOURCE_TYPE,
    ConnectionPortableCodec,
    ConnectionPortableSnapshot,
    ConnectorRequirementMetadata,
    connection_runtime_exclusions,
    register_connector_portability_codec,
    secret_reference_requirement_identifier,
    snapshot_connection,
)
from .connector_import import ConnectionImportMutationHandler, ConnectionImportPolicy
from .dependencies import ResourceDependencyRef, parse_resource_dependency, resource_dependency
from .evaluation_codecs import (
    EVALUATION_FIXTURE_RESOURCE_TYPE,
    EVALUATION_SUITE_PORTABLE_SCHEMA_VERSION,
    EVALUATION_SUITE_RESOURCE_TYPE,
    EvaluationSuitePortableCodec,
    register_evaluation_suite_portability_codec,
)
from .evaluation_import import EvaluationSuiteImportMutationHandler, EvaluationSuiteImportToken
from .executor import (
    AppliedImportResource,
    ImportExecutionResult,
    ImportExecutor,
    ImportMutationHandler,
    ImportMutationRegistry,
)
from .file_codecs import (
    ARTIFACT_RESOURCE_TYPE,
    FILE_PORTABLE_SCHEMA_VERSION,
    FILE_RESOURCE_TYPE,
    ArtifactPortableCodec,
    FilePortableCodec,
    FilePortableSnapshot,
    materialize_file,
    register_file_portability_codecs,
    snapshot_file,
)
from .file_import import FileImportMutationHandler
from .history_codecs import (
    TASK_HISTORY_PORTABLE_SCHEMA_VERSION,
    TASK_HISTORY_RESOURCE_TYPE,
    HistoricalRunSnapshot,
    HistoricalTaskSnapshot,
    TaskHistoryPortableCodec,
    register_task_history_portability_codec,
    snapshot_task_history,
)
from .history_import import (
    HistoricalTaskArchiveRepository,
    InMemoryHistoricalTaskArchiveRepository,
    TaskHistoryImportMutationHandler,
)
from .knowledge_codecs import (
    KNOWLEDGE_PORTABLE_SCHEMA_VERSION,
    KNOWLEDGE_SOURCE_RESOURCE_TYPE,
    KnowledgePortableSnapshot,
    KnowledgeSourcePortableCodec,
    knowledge_index_exclusion,
    register_knowledge_portability_codec,
)
from .knowledge_import import (
    KnowledgeImportPrivacyPolicy,
    KnowledgeSourceImportMutationHandler,
)
from .memory_codecs import (
    MEMORY_PORTABLE_SCHEMA_VERSION,
    MEMORY_RESOURCE_TYPE,
    MemoryPortableCodec,
    MemoryPortableSnapshot,
    register_memory_portability_codec,
    snapshot_memory,
)
from .memory_import import (
    MemoryImportMutationHandler,
    MemoryImportPrivacyPolicy,
)
from .model_routing_profile_codecs import (
    MODEL_ROUTING_PROFILE_PORTABLE_SCHEMA_VERSION,
    MODEL_ROUTING_PROFILE_RESOURCE_TYPE,
    ModelRoutingProfilePortableCodec,
    ModelRoutingProfilePortableSnapshot,
    register_model_routing_profile_portability_codec,
    snapshot_model_routing_profile,
)
from .model_routing_profile_import import ModelRoutingProfileImportMutationHandler
from .models import (
    PORTABLE_FORMAT_VERSION,
    PORTABLE_INTEGRITY_ALGORITHM,
    CompatibilityMetadata,
    DependencyKind,
    DependencyRequirement,
    ExcludedState,
    ExclusionCategory,
    IdPolicy,
    PackageProvenance,
    PortablePackage,
    PortablePackageManifest,
    PortableResource,
    PortableResourceDescriptor,
)
from .package import (
    build_package,
    package_from_dict,
    package_to_dict,
    seal_resource,
    verify_package,
    verify_resource,
)
from .planner import (
    ImportConflict,
    ImportConflictKind,
    ImportPreview,
    ImportPreviewService,
    MissingDependency,
    PlannedResource,
)
from .project_codecs import (
    PROJECT_PORTABLE_SCHEMA_VERSION,
    PROJECT_RESOURCE_TYPE,
    ProjectPortableCodec,
    register_project_portability_codec,
)
from .project_import import ProjectDependencyAudit, ProjectImportMutationHandler
from .registry import ImportContext, ResourceCodec, ResourceExport, ResourceSerializerRegistry
from .schema import PORTABLE_PACKAGE_SCHEMA_V1, validate_package_document
from .template_codecs import (
    TEMPLATE_PORTABLE_SCHEMA_VERSION,
    TEMPLATE_RESOURCE_TYPE,
    TemplatePortableCodec,
    TemplatePortableSnapshot,
    register_template_portability_codec,
    snapshot_template,
)
from .template_import import TemplateImportMutationHandler
from .validation import find_runtime_private_path, validate_portable_payload
from .workflow import (
    ExportSelection,
    ExportSourceRegistry,
    ImportReport,
    PackageInspection,
    PortabilityWorkflowService,
    StoredImportPreview,
    import_preview_to_dict,
    import_report_to_dict,
    package_inspection_to_dict,
)

__all__ = [
    "AGENT_PORTABLE_SCHEMA_VERSION",
    "AGENT_RESOURCE_TYPE",
    "AGENT_TEAM_RESOURCE_TYPE",
    "ARTIFACT_RESOURCE_TYPE",
    "AUTOMATION_PORTABLE_SCHEMA_VERSION",
    "AUTOMATION_RESOURCE_TYPE",
    "CONNECTION_PORTABLE_SCHEMA_VERSION",
    "CONNECTION_RESOURCE_TYPE",
    "EVALUATION_FIXTURE_RESOURCE_TYPE",
    "EVALUATION_SUITE_PORTABLE_SCHEMA_VERSION",
    "EVALUATION_SUITE_RESOURCE_TYPE",
    "FILE_PORTABLE_SCHEMA_VERSION",
    "FILE_RESOURCE_TYPE",
    "KNOWLEDGE_PORTABLE_SCHEMA_VERSION",
    "KNOWLEDGE_SOURCE_RESOURCE_TYPE",
    "MEMORY_PORTABLE_SCHEMA_VERSION",
    "MEMORY_RESOURCE_TYPE",
    "MODEL_ROUTING_PROFILE_PORTABLE_SCHEMA_VERSION",
    "MODEL_ROUTING_PROFILE_RESOURCE_TYPE",
    "PORTABLE_FORMAT_VERSION",
    "PORTABLE_INTEGRITY_ALGORITHM",
    "PORTABLE_PACKAGE_SCHEMA_V1",
    "PROJECT_PORTABLE_SCHEMA_VERSION",
    "PROJECT_RESOURCE_TYPE",
    "TASK_HISTORY_PORTABLE_SCHEMA_VERSION",
    "TASK_HISTORY_RESOURCE_TYPE",
    "TEMPLATE_PORTABLE_SCHEMA_VERSION",
    "TEMPLATE_RESOURCE_TYPE",
    "AgentImportMutationHandler",
    "AgentPortableCodec",
    "AgentPortableSnapshot",
    "AgentTeamImportMutationHandler",
    "AgentTeamPortableCodec",
    "AgentTeamPortableSnapshot",
    "AppliedImportResource",
    "ArtifactPortableCodec",
    "AutomationImportMutationHandler",
    "AutomationImportPolicy",
    "AutomationPortableCodec",
    "AutomationPortableSnapshot",
    "CompatibilityMetadata",
    "ConnectionImportMutationHandler",
    "ConnectionImportPolicy",
    "ConnectionPortableCodec",
    "ConnectionPortableSnapshot",
    "ConnectorRequirementMetadata",
    "DependencyKind",
    "DependencyRequirement",
    "EvaluationSuiteImportMutationHandler",
    "EvaluationSuiteImportToken",
    "EvaluationSuitePortableCodec",
    "ExcludedState",
    "ExclusionCategory",
    "ExportSelection",
    "ExportSourceRegistry",
    "FileImportMutationHandler",
    "FilePortableCodec",
    "FilePortableSnapshot",
    "HistoricalRunSnapshot",
    "HistoricalTaskArchiveRepository",
    "HistoricalTaskSnapshot",
    "IdPolicy",
    "ImportConflict",
    "ImportConflictKind",
    "ImportContext",
    "ImportExecutionResult",
    "ImportExecutor",
    "ImportMutationHandler",
    "ImportMutationRegistry",
    "ImportPreview",
    "ImportPreviewService",
    "ImportReport",
    "InMemoryHistoricalTaskArchiveRepository",
    "KnowledgeImportPrivacyPolicy",
    "KnowledgePortableSnapshot",
    "KnowledgeSourceImportMutationHandler",
    "KnowledgeSourcePortableCodec",
    "MemoryImportMutationHandler",
    "MemoryImportPrivacyPolicy",
    "MemoryPortableCodec",
    "MemoryPortableSnapshot",
    "MissingDependency",
    "ModelRoutingProfileImportMutationHandler",
    "ModelRoutingProfilePortableCodec",
    "ModelRoutingProfilePortableSnapshot",
    "PackageInspection",
    "PackageProvenance",
    "PlannedResource",
    "PortabilityWorkflowService",
    "PortablePackage",
    "PortablePackageManifest",
    "PortableResource",
    "PortableResourceDescriptor",
    "ProjectDependencyAudit",
    "ProjectImportMutationHandler",
    "ProjectPortableCodec",
    "ResourceCodec",
    "ResourceDependencyRef",
    "ResourceExport",
    "ResourceSerializerRegistry",
    "StoredImportPreview",
    "TaskHistoryImportMutationHandler",
    "TaskHistoryPortableCodec",
    "TemplateImportMutationHandler",
    "TemplatePortableCodec",
    "TemplatePortableSnapshot",
    "automation_runtime_exclusions",
    "build_package",
    "connection_runtime_exclusions",
    "find_runtime_private_path",
    "import_preview_to_dict",
    "import_report_to_dict",
    "knowledge_index_exclusion",
    "materialize_file",
    "package_from_dict",
    "package_inspection_to_dict",
    "package_to_dict",
    "parse_resource_dependency",
    "register_agent_portability_codecs",
    "register_automation_portability_codec",
    "register_connector_portability_codec",
    "register_evaluation_suite_portability_codec",
    "register_file_portability_codecs",
    "register_knowledge_portability_codec",
    "register_memory_portability_codec",
    "register_model_routing_profile_portability_codec",
    "register_project_portability_codec",
    "register_task_history_portability_codec",
    "register_template_portability_codec",
    "resource_dependency",
    "seal_resource",
    "secret_reference_requirement_identifier",
    "snapshot_agent",
    "snapshot_agent_team",
    "snapshot_automation",
    "snapshot_connection",
    "snapshot_file",
    "snapshot_memory",
    "snapshot_model_routing_profile",
    "snapshot_task_history",
    "snapshot_template",
    "validate_package_document",
    "validate_portable_payload",
    "verify_package",
    "verify_resource",
]
