"""Portable canonical import/export contracts for issue #79."""

from .agent_codecs import (
    AGENT_PORTABLE_SCHEMA_VERSION,
    AGENT_RESOURCE_TYPE,
    AGENT_TEAM_RESOURCE_TYPE,
    AgentPortableCodec,
    AgentPortableSnapshot,
    AgentTeamPortableCodec,
    AgentTeamPortableSnapshot,
    register_agent_portability_codecs,
    snapshot_agent,
    snapshot_agent_team,
)
from .agent_import import AgentImportMutationHandler, AgentTeamImportMutationHandler
from .automation_codecs import (
    AUTOMATION_PORTABLE_SCHEMA_VERSION,
    AUTOMATION_RESOURCE_TYPE,
    AutomationPortableCodec,
    AutomationPortableSnapshot,
    automation_runtime_exclusions,
    register_automation_portability_codec,
    snapshot_automation,
)
from .automation_import import AutomationImportMutationHandler, AutomationImportPolicy
from .dependencies import ResourceDependencyRef, parse_resource_dependency, resource_dependency
from .executor import (
    AppliedImportResource,
    ImportExecutionResult,
    ImportExecutor,
    ImportMutationHandler,
    ImportMutationRegistry,
)
from .file_codecs import (
    ARTIFACT_RESOURCE_TYPE,
    FILE_PORTABLE_SCHEMA_VERSION,
    FILE_RESOURCE_TYPE,
    ArtifactPortableCodec,
    FilePortableCodec,
    FilePortableSnapshot,
    materialize_file,
    register_file_portability_codecs,
    snapshot_file,
)
from .file_import import FileImportMutationHandler
from .history_codecs import (
    TASK_HISTORY_PORTABLE_SCHEMA_VERSION,
    TASK_HISTORY_RESOURCE_TYPE,
    HistoricalRunSnapshot,
    HistoricalTaskSnapshot,
    TaskHistoryPortableCodec,
    register_task_history_portability_codec,
    snapshot_task_history,
)
from .history_import import (
    HistoricalTaskArchiveRepository,
    InMemoryHistoricalTaskArchiveRepository,
    TaskHistoryImportMutationHandler,
)
from .knowledge_codecs import (
    KNOWLEDGE_PORTABLE_SCHEMA_VERSION,
    KNOWLEDGE_SOURCE_RESOURCE_TYPE,
    KnowledgePortableSnapshot,
    KnowledgeSourcePortableCodec,
    knowledge_index_exclusion,
    register_knowledge_portability_codec,
)
from .knowledge_import import (
    KnowledgeImportPrivacyPolicy,
    KnowledgeSourceImportMutationHandler,
)
from .memory_codecs import (
    MEMORY_PORTABLE_SCHEMA_VERSION,
    MEMORY_RESOURCE_TYPE,
    MemoryPortableCodec,
    MemoryPortableSnapshot,
    register_memory_portability_codec,
    snapshot_memory,
)
from .memory_import import (
    MemoryImportMutationHandler,
    MemoryImportPrivacyPolicy,
)
from .models import (
    PORTABLE_FORMAT_VERSION,
    PORTABLE_INTEGRITY_ALGORITHM,
    CompatibilityMetadata,
    DependencyKind,
    DependencyRequirement,
    ExcludedState,
    ExclusionCategory,
    IdPolicy,
    PackageProvenance,
    PortablePackage,
    PortablePackageManifest,
    PortableResource,
    PortableResourceDescriptor,
)
from .package import (
    build_package,
    package_from_dict,
    package_to_dict,
    seal_resource,
    verify_package,
    verify_resource,
)
from .planner import (
    ImportConflict,
    ImportConflictKind,
    ImportPreview,
    ImportPreviewService,
    MissingDependency,
    PlannedResource,
)
from .registry import ImportContext, ResourceCodec, ResourceExport, ResourceSerializerRegistry
from .schema import PORTABLE_PACKAGE_SCHEMA_V1, validate_package_document
from .validation import find_runtime_private_path, validate_portable_payload

__all__ = [
    "AGENT_PORTABLE_SCHEMA_VERSION",
    "AGENT_RESOURCE_TYPE",
    "AGENT_TEAM_RESOURCE_TYPE",
    "ARTIFACT_RESOURCE_TYPE",
    "AUTOMATION_PORTABLE_SCHEMA_VERSION",
    "AUTOMATION_RESOURCE_TYPE",
    "FILE_PORTABLE_SCHEMA_VERSION",
    "FILE_RESOURCE_TYPE",
    "KNOWLEDGE_PORTABLE_SCHEMA_VERSION",
    "KNOWLEDGE_SOURCE_RESOURCE_TYPE",
    "MEMORY_PORTABLE_SCHEMA_VERSION",
    "MEMORY_RESOURCE_TYPE",
    "PORTABLE_FORMAT_VERSION",
    "PORTABLE_INTEGRITY_ALGORITHM",
    "PORTABLE_PACKAGE_SCHEMA_V1",
    "TASK_HISTORY_PORTABLE_SCHEMA_VERSION",
    "TASK_HISTORY_RESOURCE_TYPE",
    "AgentImportMutationHandler",
    "AgentPortableCodec",
    "AgentPortableSnapshot",
    "AgentTeamImportMutationHandler",
    "AgentTeamPortableCodec",
    "AgentTeamPortableSnapshot",
    "AppliedImportResource",
    "ArtifactPortableCodec",
    "AutomationImportMutationHandler",
    "AutomationImportPolicy",
    "AutomationPortableCodec",
    "AutomationPortableSnapshot",
    "CompatibilityMetadata",
    "DependencyKind",
    "DependencyRequirement",
    "ExcludedState",
    "ExclusionCategory",
    "FileImportMutationHandler",
    "FilePortableCodec",
    "FilePortableSnapshot",
    "HistoricalRunSnapshot",
    "HistoricalTaskArchiveRepository",
    "HistoricalTaskSnapshot",
    "IdPolicy",
    "ImportConflict",
    "ImportConflictKind",
    "ImportContext",
    "ImportExecutionResult",
    "ImportExecutor",
    "ImportMutationHandler",
    "ImportMutationRegistry",
    "ImportPreview",
    "ImportPreviewService",
    "InMemoryHistoricalTaskArchiveRepository",
    "KnowledgeImportPrivacyPolicy",
    "KnowledgePortableSnapshot",
    "KnowledgeSourceImportMutationHandler",
    "KnowledgeSourcePortableCodec",
    "MemoryImportMutationHandler",
    "MemoryImportPrivacyPolicy",
    "MemoryPortableCodec",
    "MemoryPortableSnapshot",
    "MissingDependency",
    "PackageProvenance",
    "PlannedResource",
    "PortablePackage",
    "PortablePackageManifest",
    "PortableResource",
    "PortableResourceDescriptor",
    "ResourceCodec",
    "ResourceDependencyRef",
    "ResourceExport",
    "ResourceSerializerRegistry",
    "TaskHistoryImportMutationHandler",
    "TaskHistoryPortableCodec",
    "automation_runtime_exclusions",
    "build_package",
    "find_runtime_private_path",
    "knowledge_index_exclusion",
    "materialize_file",
    "package_from_dict",
    "package_to_dict",
    "parse_resource_dependency",
    "register_agent_portability_codecs",
    "register_automation_portability_codec",
    "register_file_portability_codecs",
    "register_knowledge_portability_codec",
    "register_memory_portability_codec",
    "register_task_history_portability_codec",
    "resource_dependency",
    "seal_resource",
    "snapshot_agent",
    "snapshot_agent_team",
    "snapshot_automation",
    "snapshot_file",
    "snapshot_memory",
    "snapshot_task_history",
    "validate_package_document",
    "validate_portable_payload",
    "verify_package",
    "verify_resource",
]
