"""Cross-cutting platform security, authentication and authorization surface."""

# Import order is intentionally not fully alphabetical: redaction/types must be bound
# before enforced_providers imports configuration, whose package root imports them back.
# ruff: noqa: I001

from ai_multi_agent_platform.contracts import AuthorizationOutcome

from .approvals import ApprovalRecord, ApprovalService
from .authentication import (
    AuthenticatedActor,
    AuthenticationAuditRecord,
    AuthenticationError,
    AuthenticationFailure,
    AuthenticationMethod,
    AuthenticationRateLimiter,
    BrowserSession,
    CredentialKind,
    ExternalIdentityMapping,
    IdentityProviderAdapter,
    InMemoryAuthenticationStore,
    InMemoryFailureRateLimiter,
    InMemoryReplayProtector,
    IssuedCredential,
    LocalUserAccount,
    LoginResult,
    ReplayProtector,
    ScryptPasswordHasher,
    SessionGrant,
    StoredCredential,
    VerifiedExternalIdentity,
    safe_actor,
    safe_credential,
    safe_session,
)
from .authentication_hardening import (
    AuthenticationRequestRateLimiter,
    CredentialRotation,
    CredentialScope,
    InMemoryRequestRateLimiter,
    LocalAuthenticationService,
    safe_credential_with_scope,
)
from .authorization import (
    ActorIdentity,
    ActorType,
    AuthorizationAction,
    AuthorizationAuditRecord,
    AuthorizationContext,
    LocalAuthorizationProvider,
    LocalPrincipalPolicy,
    ProposedAction,
    ResourceType,
    RiskClassification,
    infer_actor_identity,
)
from .control_plane_bridge import (
    ControlPlaneAuthorizationBridge,
    canonical_control_plane_vocabulary,
)
from .data_enforcement import AuthorizedDataFileProvider
from .data_enforcement_lifecycle import (
    AuthorizedDataKnowledgeProvider,
    AuthorizedDataMemoryProvider,
)
from .enforcement import AuthorizationAuditSink, AuthorizationGate
from .paths import PathSecurityError, resolve_within
from .policy import baseline_decision
from .policy_profile_persistence import (
    POLICY_PROFILE_REPOSITORY_SCHEMA_VERSION,
    JsonAuthorizationPolicyProfileRepository,
    policy_profile_revision_from_json,
    policy_profile_revision_to_json,
)
from .policy_profiles import (
    POLICY_PROFILE_SCHEMA_VERSION,
    AuthorizationPolicyAssignment,
    AuthorizationPolicyConditions,
    AuthorizationPolicyProfileCallContext,
    AuthorizationPolicyProfileContent,
    AuthorizationPolicyProfileDefinition,
    AuthorizationPolicyProfileRef,
    AuthorizationPolicyProfileRepository,
    AuthorizationPolicyProfileRevision,
    AuthorizationPolicyProfileService,
    AuthorizationPolicyProvenance,
    AuthorizationPolicyScopeConstraints,
    InMemoryAuthorizationPolicyProfileRepository,
    compile_local_principal_policy,
)
from .redaction import REDACTED, redact_exception, redact_sensitive, redact_text
from .sqlite_approvals import SqliteApprovalService, SqliteAuthorizationAuditSink
from .types import (
    ExternalSideEffect,
    SecretReference,
    SecurityAuditEvent,
    SecurityContext,
    SecurityDecision,
)
from .enforced_providers import (
    AuthorizedFileProvider,
    AuthorizedKnowledgeProvider,
    AuthorizedLifecycleBackend,
    AuthorizedMemoryProvider,
    AuthorizedSecretProvider,
    AuthorizedToolProvider,
)
from .validation import UntrustedInputError, validate_untrusted_json

__all__ = [
    "POLICY_PROFILE_REPOSITORY_SCHEMA_VERSION",
    "POLICY_PROFILE_SCHEMA_VERSION",
    "REDACTED",
    "ActorIdentity",
    "ActorType",
    "ApprovalRecord",
    "ApprovalService",
    "AuthenticatedActor",
    "AuthenticationAuditRecord",
    "AuthenticationError",
    "AuthenticationFailure",
    "AuthenticationMethod",
    "AuthenticationRateLimiter",
    "AuthenticationRequestRateLimiter",
    "AuthorizationAction",
    "AuthorizationAuditRecord",
    "AuthorizationAuditSink",
    "AuthorizationContext",
    "AuthorizationGate",
    "AuthorizationOutcome",
    "AuthorizationPolicyAssignment",
    "AuthorizationPolicyConditions",
    "AuthorizationPolicyProfileCallContext",
    "AuthorizationPolicyProfileContent",
    "AuthorizationPolicyProfileDefinition",
    "AuthorizationPolicyProfileRef",
    "AuthorizationPolicyProfileRepository",
    "AuthorizationPolicyProfileRevision",
    "AuthorizationPolicyProfileService",
    "AuthorizationPolicyProvenance",
    "AuthorizationPolicyScopeConstraints",
    "AuthorizedDataFileProvider",
    "AuthorizedDataKnowledgeProvider",
    "AuthorizedDataMemoryProvider",
    "AuthorizedFileProvider",
    "AuthorizedKnowledgeProvider",
    "AuthorizedLifecycleBackend",
    "AuthorizedMemoryProvider",
    "AuthorizedSecretProvider",
    "AuthorizedToolProvider",
    "BrowserSession",
    "ControlPlaneAuthorizationBridge",
    "CredentialKind",
    "CredentialRotation",
    "CredentialScope",
    "ExternalIdentityMapping",
    "ExternalSideEffect",
    "IdentityProviderAdapter",
    "InMemoryAuthenticationStore",
    "InMemoryAuthorizationPolicyProfileRepository",
    "InMemoryFailureRateLimiter",
    "InMemoryReplayProtector",
    "InMemoryRequestRateLimiter",
    "IssuedCredential",
    "JsonAuthorizationPolicyProfileRepository",
    "LocalAuthenticationService",
    "LocalAuthorizationProvider",
    "LocalPrincipalPolicy",
    "LocalUserAccount",
    "LoginResult",
    "PathSecurityError",
    "ProposedAction",
    "ReplayProtector",
    "ResourceType",
    "RiskClassification",
    "ScryptPasswordHasher",
    "SecretReference",
    "SecurityAuditEvent",
    "SecurityContext",
    "SecurityDecision",
    "SessionGrant",
    "SqliteApprovalService",
    "SqliteAuthorizationAuditSink",
    "StoredCredential",
    "UntrustedInputError",
    "VerifiedExternalIdentity",
    "baseline_decision",
    "canonical_control_plane_vocabulary",
    "compile_local_principal_policy",
    "infer_actor_identity",
    "policy_profile_revision_from_json",
    "policy_profile_revision_to_json",
    "redact_exception",
    "redact_sensitive",
    "redact_text",
    "resolve_within",
    "safe_actor",
    "safe_credential",
    "safe_credential_with_scope",
    "safe_session",
    "validate_untrusted_json",
]
