"""Cross-cutting platform security, authentication and authorization surface."""

from .approvals import ApprovalRecord, ApprovalService
from .authentication import (
    AuthenticatedActor,
    AuthenticationAuditRecord,
    AuthenticationError,
    AuthenticationFailure,
    AuthenticationMethod,
    AuthenticationRateLimiter,
    BrowserSession,
    CredentialKind,
    ExternalIdentityMapping,
    IdentityProviderAdapter,
    InMemoryAuthenticationStore,
    InMemoryFailureRateLimiter,
    InMemoryReplayProtector,
    IssuedCredential,
    LocalAuthenticationService,
    LocalUserAccount,
    LoginResult,
    ReplayProtector,
    ScryptPasswordHasher,
    SessionGrant,
    StoredCredential,
    VerifiedExternalIdentity,
    safe_actor,
    safe_credential,
    safe_session,
)
from .authorization import (
    ActorIdentity,
    ActorType,
    AuthorizationAction,
    AuthorizationAuditRecord,
    AuthorizationContext,
    LocalAuthorizationProvider,
    LocalPrincipalPolicy,
    ProposedAction,
    ResourceType,
    RiskClassification,
    infer_actor_identity,
)
from .control_plane_bridge import (
    ControlPlaneAuthorizationBridge,
    canonical_control_plane_vocabulary,
)
from .data_enforcement import (
    AuthorizedDataFileProvider,
    AuthorizedDataKnowledgeProvider,
    AuthorizedDataMemoryProvider,
)
from .enforcement import AuthorizationAuditSink, AuthorizationGate
from .paths import PathSecurityError, resolve_within
from .policy import baseline_decision
from .redaction import REDACTED, redact_exception, redact_sensitive, redact_text
from .types import (
    ExternalSideEffect,
    SecretReference,
    SecurityAuditEvent,
    SecurityContext,
    SecurityDecision,
)
from .validation import UntrustedInputError, validate_untrusted_json

__all__ = [
    "REDACTED",
    "ActorIdentity",
    "ActorType",
    "ApprovalRecord",
    "ApprovalService",
    "AuthenticatedActor",
    "AuthenticationAction",
    "AuthenticationAuditRecord",
    "AuthenticationError",
    "AuthenticationFailure",
    "AuthenticationMethod",
    "AuthenticationRateLimiter",
    "AuthorizationAction",
    "AuthorizationAuditRecord",
    "AuthorizationAuditSink",
    "AuthorizationContext",
    "AuthorizationGate",
    "AuthorizedDataFileProvider",
    "AuthorizedDataKnowledgeProvider",
    "AuthorizedDataMemoryProvider",
    "BrowserSession",
    "ControlPlaneAuthorizationBridge",
    "CredentialKind",
    "ExternalIdentityMapping",
    "ExternalSideEffect",
    "IdentityProviderAdapter",
    "InMemoryAuthenticationStore",
    "InMemoryFailureRateLimiter",
    "InMemoryReplayProtector",
    "IssuedCredential",
    "LocalAuthenticationService",
    "LocalAuthorizationProvider",
    "LocalPrincipalPolicy",
    "LocalUserAccount",
    "LoginResult",
    "PathSecurityError",
    "ProposedAction",
    "ReplayProtector",
    "ResourceType",
    "RiskClassification",
    "ScryptPasswordHasher",
    "SecretReference",
    "SecurityAuditEvent",
    "SecurityContext",
    "SecurityDecision",
    "SessionGrant",
    "StoredCredential",
    "UntrustedInputError",
    "VerifiedExternalIdentity",
    "baseline_decision",
    "canonical_control_plane_vocabulary",
    "infer_actor_identity",
    "redact_exception",
    "redact_sensitive",
    "redact_text",
    "resolve_within",
    "safe_actor",
    "safe_credential",
    "safe_session",
    "validate_untrusted_json",
]
