"""Reusable, versioned configuration Templates."""

from .agent_handlers import (
    AgentTeamTemplateHandler,
    AgentTemplateExporter,
    AgentTemplateHandler,
    register_agent_template_handlers,
)
from .application import (
    CompositeTemplateHandler,
    ContextualTemplateHandlerRegistry,
    ContextualTemplateResourceHandler,
    TemplateApplicationService,
    TemplateInstantiationContext,
)
from .models import (
    CapabilityRequirement,
    TemplateCompatibility,
    TemplateConfiguration,
    TemplateContent,
    TemplateDefinition,
    TemplateDependency,
    TemplateInstantiation,
    TemplateInstantiationProvenance,
    TemplateProvenance,
    TemplateRequirements,
    TemplateResourceChange,
    TemplateResourceRef,
    TemplateRevision,
    TemplateRevisionRef,
    TemplateRevisionState,
    TemplateTrust,
    TemplateType,
)
from .persistence import TEMPLATE_REPOSITORY_SCHEMA_VERSION, JsonTemplateRepository
from .repository import InMemoryTemplateRepository, TemplateRepository
from .service import (
    TemplateEnvironment,
    TemplateHandlerRegistry,
    TemplatePreview,
    TemplateResourceHandler,
    TemplateService,
    validate_template_configuration,
)

__all__ = [
    "AgentTeamTemplateHandler",
    "AgentTemplateExporter",
    "AgentTemplateHandler",
    "CapabilityRequirement",
    "CompositeTemplateHandler",
    "ContextualTemplateHandlerRegistry",
    "ContextualTemplateResourceHandler",
    "InMemoryTemplateRepository",
    "JsonTemplateRepository",
    "TEMPLATE_REPOSITORY_SCHEMA_VERSION",
    "TemplateApplicationService",
    "TemplateCompatibility",
    "TemplateConfiguration",
    "TemplateContent",
    "TemplateDefinition",
    "TemplateDependency",
    "TemplateEnvironment",
    "TemplateHandlerRegistry",
    "TemplateInstantiation",
    "TemplateInstantiationContext",
    "TemplateInstantiationProvenance",
    "TemplatePreview",
    "TemplateProvenance",
    "TemplateRepository",
    "TemplateRequirements",
    "TemplateResourceChange",
    "TemplateResourceHandler",
    "TemplateResourceRef",
    "TemplateRevision",
    "TemplateRevisionRef",
    "TemplateRevisionState",
    "TemplateService",
    "TemplateTrust",
    "TemplateType",
    "register_agent_template_handlers",
    "validate_template_configuration",
]
