"""Canonical capability registry and invocation pipeline."""

from .canonical_binding import (
    bind_canonical_capability_invocation,
    canonical_tool_id,
    canonical_tool_invocation_id,
)
from .egress import CapabilityClassificationResolver, EgressCapabilityInvoker
from .invocation import (
    ApprovalHook,
    CanonicalInvocationBindingHook,
    GovernanceBindingHook,
    InvocationObserver,
    NullInvocationObserver,
    PolicyHook,
)
from .native import ECHO_CAPABILITY_ID, NativeEchoProvider
from .observer import EventRepositoryInvocationObserver
from .provider import CapabilityToolProvider
from .recovery import (
    ExternalEffectInvocationObserver,
    ExternalEffectObservation,
    ExternalEffectObservationStatus,
    ExternalEffectReconciler,
    ExternalEffectReconciliationRequest,
    ExternalEffectRecoveryCoordinator,
    ExternalEffectRecoveryDisposition,
    ExternalEffectRecoveryRecord,
    ExternalEffectRecoveryRepository,
    ExternalEffectRecoveryStatus,
    InMemoryExternalEffectRecoveryRepository,
    SQLiteExternalEffectRecoveryRepository,
    external_effect_recovery_resource,
)
from .registry import CapabilityDiscoveryPolicyHook, CapabilityRegistry
from .types import (
    ISOLATED_WORKSPACE_WRITE_FEATURE,
    CapabilityCompatibilityRequest,
    CapabilityDiscoveryRequest,
    CapabilityInvocation,
    CapabilityInvocationResult,
    CapabilityRegistration,
    CapabilitySpec,
    CompensationDescriptor,
    CompensationIdempotency,
    CredentialRequirement,
    ExternalEffectIdempotency,
    ExternalEffectReconciliationSupport,
    ExternalEffectRecoveryPolicy,
    InvocationRecord,
    InvocationStatus,
    InvocationTrace,
    PolicyDecision,
    ReversibilityClassification,
    SafetyClassification,
    SideEffectClassification,
)

# Keep the established public name while making egress enforcement the default application path.
CapabilityInvoker = EgressCapabilityInvoker

__all__ = [
    "ApprovalHook",
    "CanonicalInvocationBindingHook",
    "CapabilityClassificationResolver",
    "CapabilityCompatibilityRequest",
    "CapabilityDiscoveryPolicyHook",
    "CapabilityDiscoveryRequest",
    "CapabilityInvocation",
    "CapabilityInvocationResult",
    "CapabilityInvoker",
    "CapabilityRegistration",
    "CapabilityRegistry",
    "CapabilitySpec",
    "CapabilityToolProvider",
    "CompensationDescriptor",
    "CompensationIdempotency",
    "CredentialRequirement",
    "ECHO_CAPABILITY_ID",
    "EgressCapabilityInvoker",
    "ExternalEffectIdempotency",
    "ExternalEffectInvocationObserver",
    "ExternalEffectObservation",
    "ExternalEffectObservationStatus",
    "ExternalEffectReconciler",
    "ExternalEffectReconciliationRequest",
    "ExternalEffectReconciliationSupport",
    "ExternalEffectRecoveryCoordinator",
    "ExternalEffectRecoveryDisposition",
    "ExternalEffectRecoveryPolicy",
    "ExternalEffectRecoveryRecord",
    "ExternalEffectRecoveryRepository",
    "ExternalEffectRecoveryStatus",
    "EventRepositoryInvocationObserver",
    "GovernanceBindingHook",
    "ISOLATED_WORKSPACE_WRITE_FEATURE",
    "InvocationObserver",
    "InvocationRecord",
    "InvocationStatus",
    "InvocationTrace",
    "InMemoryExternalEffectRecoveryRepository",
    "NativeEchoProvider",
    "NullInvocationObserver",
    "PolicyDecision",
    "PolicyHook",
    "ReversibilityClassification",
    "SafetyClassification",
    "SideEffectClassification",
    "SQLiteExternalEffectRecoveryRepository",
    "bind_canonical_capability_invocation",
    "canonical_tool_id",
    "canonical_tool_invocation_id",
    "external_effect_recovery_resource",
]
