"""Canonical structured work-transfer contracts for Agents and Agent Teams."""

from .context import ConsumedHandoffContextAdapter, handoff_context_candidate
from .control_plane import HandoffControlPlaneProjection, HandoffViewAuthorizer
from .control_plane_resources import (
    HANDOFF_COLLECTION,
    HANDOFF_CONSUMPTION_COLLECTION,
    HandoffConsumptionResourceService,
    HandoffResourceService,
    register_handoff_control_plane,
)
from .coordination import CoordinatedHandoffService
from .models import (
    HANDOFF_SCHEMA_VERSION,
    AgentHandoff,
    HandoffAuditEvent,
    HandoffConsumption,
    HandoffContent,
    HandoffContextSource,
    HandoffRuntimeContext,
    HandoffSourceKind,
    HandoffSourceRef,
    ParticipantRef,
    build_handoff,
    compute_creation_request_digest,
    compute_handoff_digest,
    consumption_from_dict,
    consumption_to_dict,
    handoff_context_source,
    handoff_from_dict,
    handoff_to_dict,
    new_handoff_id,
    participant_key,
)
from .production import (
    CanonicalConsumerRequirementEvaluator,
    CanonicalHandoffReferenceGateway,
    DurableConsumedHandoffContextAdapter,
    HandoffConsumerExecution,
    ProductionHandoffRuntime,
    TelemetryHandoffAuditSink,
    build_production_handoff_runtime,
)
from .repository import HandoffRepository, InMemoryHandoffRepository, SQLiteHandoffRepository
from .service import (
    ConsumerRequirementEvaluator,
    HandoffAgentRevisionRepository,
    HandoffAuditSink,
    HandoffReferenceGateway,
    HandoffService,
    InMemoryHandoffAuditSink,
    NullHandoffAuditSink,
)

__all__ = [
    "HANDOFF_COLLECTION",
    "HANDOFF_CONSUMPTION_COLLECTION",
    "HANDOFF_SCHEMA_VERSION",
    "AgentHandoff",
    "CanonicalConsumerRequirementEvaluator",
    "CanonicalHandoffReferenceGateway",
    "ConsumedHandoffContextAdapter",
    "ConsumerRequirementEvaluator",
    "CoordinatedHandoffService",
    "DurableConsumedHandoffContextAdapter",
    "HandoffAgentRevisionRepository",
    "HandoffAuditEvent",
    "HandoffAuditSink",
    "HandoffConsumption",
    "HandoffConsumptionResourceService",
    "HandoffConsumerExecution",
    "HandoffContent",
    "HandoffContextSource",
    "HandoffControlPlaneProjection",
    "HandoffReferenceGateway",
    "HandoffRepository",
    "HandoffResourceService",
    "HandoffRuntimeContext",
    "HandoffService",
    "HandoffSourceKind",
    "HandoffSourceRef",
    "HandoffViewAuthorizer",
    "InMemoryHandoffAuditSink",
    "InMemoryHandoffRepository",
    "NullHandoffAuditSink",
    "ParticipantRef",
    "ProductionHandoffRuntime",
    "SQLiteHandoffRepository",
    "TelemetryHandoffAuditSink",
    "build_handoff",
    "build_production_handoff_runtime",
    "compute_creation_request_digest",
    "compute_handoff_digest",
    "consumption_from_dict",
    "consumption_to_dict",
    "handoff_context_candidate",
    "handoff_context_source",
    "handoff_from_dict",
    "handoff_to_dict",
    "new_handoff_id",
    "participant_key",
    "register_handoff_control_plane",
]
