"""Canonical structured work-transfer contracts for Agents and Agent Teams."""

from .control_plane import HandoffControlPlaneProjection, HandoffViewAuthorizer
from .coordination import CoordinatedHandoffService
from .models import (
    HANDOFF_SCHEMA_VERSION,
    AgentHandoff,
    HandoffAuditEvent,
    HandoffConsumption,
    HandoffContent,
    HandoffContextSource,
    HandoffRuntimeContext,
    HandoffSourceKind,
    HandoffSourceRef,
    ParticipantRef,
    build_handoff,
    compute_creation_request_digest,
    compute_handoff_digest,
    consumption_from_dict,
    consumption_to_dict,
    handoff_context_source,
    handoff_from_dict,
    handoff_to_dict,
    new_handoff_id,
    participant_key,
)
from .repository import HandoffRepository, InMemoryHandoffRepository, SQLiteHandoffRepository
from .service import (
    ConsumerRequirementEvaluator,
    HandoffAgentRevisionRepository,
    HandoffAuditSink,
    HandoffReferenceGateway,
    HandoffService,
    InMemoryHandoffAuditSink,
    NullHandoffAuditSink,
)

__all__ = [
    "HANDOFF_SCHEMA_VERSION",
    "AgentHandoff",
    "ConsumerRequirementEvaluator",
    "CoordinatedHandoffService",
    "HandoffAgentRevisionRepository",
    "HandoffAuditEvent",
    "HandoffAuditSink",
    "HandoffConsumption",
    "HandoffContent",
    "HandoffContextSource",
    "HandoffControlPlaneProjection",
    "HandoffReferenceGateway",
    "HandoffRepository",
    "HandoffRuntimeContext",
    "HandoffService",
    "HandoffSourceKind",
    "HandoffSourceRef",
    "HandoffViewAuthorizer",
    "InMemoryHandoffAuditSink",
    "InMemoryHandoffRepository",
    "NullHandoffAuditSink",
    "ParticipantRef",
    "SQLiteHandoffRepository",
    "build_handoff",
    "compute_creation_request_digest",
    "compute_handoff_digest",
    "consumption_from_dict",
    "consumption_to_dict",
    "handoff_context_source",
    "handoff_from_dict",
    "handoff_to_dict",
    "new_handoff_id",
    "participant_key",
]
