"""Optional registry and Marketplace distribution contracts."""

from .canonical_router import (
    CanonicalDistributionRouter,
    PluginArtifactInstaller,
    PortabilityImportOwner,
)
from .composition import PlatformRegistryValidationContextResolver
from .control_plane import (
    REGISTRY_ACTIVATE_COMMAND,
    REGISTRY_COLLECTION,
    REGISTRY_PIN_COMMAND,
    REGISTRY_PREVIEW_COMMAND,
    REGISTRY_UNPIN_COMMAND,
    RegistryCommandHandlers,
    RegistryResourceService,
    RegistryValidationContextResolver,
    register_distribution_control_plane,
)
from .decision_types import (
    ApprovalRequirement,
    CompatibilityDecision,
    DependencyResolution,
    DependencyStatus,
    DistributionOperation,
    MarketplaceDecision,
    PermissionDiff,
    ProvenanceDiff,
    UpdateState,
)
from .dependency_graph import evaluate_compatibility, resolve_dependency_graph
from .discovery import (
    CuratedCandidateReview,
    DiscoveryCandidate,
    RegistryDiscoverySource,
    curate_discovered_candidate,
)
from .filesystem import FilesystemRegistryProvider
from .handlers import MarketplaceKindHandler, MarketplaceKindHandlerRegistry
from .items import InstalledRegistryItem, RegistryItem, RegistryQuery
from .kinds import (
    BUILTIN_MARKETPLACE_KINDS,
    MarketplaceKindDescriptor,
    MarketplaceKindRegistry,
    builtin_marketplace_kind,
    marketplace_kind_registry_with_builtins,
)
from .local import LocalRegistryProvider
from .models import (
    ArtifactIntegrity,
    DistributionRoute,
    RegistryCompatibility,
    RegistryDependency,
    RegistryItemKind,
    RegistryItemType,
    RegistryManifestReference,
    RegistrySource,
    TrustStatus,
    VersionRange,
    parse_registry_item_kind,
    registry_item_kind_value,
)
from .plugin_adapter import PluginRegistryArtifactInstaller
from .provider import (
    MultiRegistryProvider,
    RegistryItemNotFoundError,
    RegistryProvider,
    RegistrySourceConflictError,
    RegistryUnavailableError,
    SourcedRegistryProvider,
)
from .reconciliation import RegistryPluginReconciliationError, reconcile_registry_plugins
from .schema import (
    REGISTRY_ITEM_SCHEMA_VERSION,
    registry_item_from_document,
    validate_registry_item_document,
)
from .service import (
    DistributionPreview,
    DistributionRouter,
    DistributionService,
    DistributionUninstallPreview,
)
from .signatures import (
    HmacSha256SignatureVerifier,
    RegistrySignatureVerifier,
    load_hmac_signature_keys,
)
from .state import (
    JsonRegistryInstallationStore,
    RegistryInstallation,
    RegistryInstallationSnapshot,
    RegistryInstallationStore,
)
from .technical_catalog import (
    TECHNICAL_CATEGORIES,
    TECHNICAL_COST_STATUSES,
    TECHNICAL_DEPLOYMENT_MODES,
    TECHNICAL_EVALUATION_STATUSES,
    TECHNICAL_LIFECYCLE_STATUSES,
    TECHNICAL_NETWORK_STATUSES,
    TechnicalMarketplaceMetadata,
    derive_technical_metadata,
    is_technical_component,
)
from .validation import (
    FindingCategory,
    FindingSeverity,
    ValidationContext,
    ValidationFinding,
    has_errors,
    validate_item,
)

__all__ = [
    "resolve_dependency_graph",
    "evaluate_compatibility",
    "UpdateState",
    "SourcedRegistryProvider",
    "RegistrySourceConflictError",
    "RegistryCompatibility",
    "ProvenanceDiff",
    "PermissionDiff",
    "MultiRegistryProvider",
    "MarketplaceDecision",
    "FindingCategory",
    "DistributionUninstallPreview",
    "DistributionOperation",
    "DependencyStatus",
    "DependencyResolution",
    "CompatibilityDecision",
    "ApprovalRequirement",
    "ArtifactIntegrity",
    "BUILTIN_MARKETPLACE_KINDS",
    "CanonicalDistributionRouter",
    "CuratedCandidateReview",
    "DiscoveryCandidate",
    "DistributionPreview",
    "DistributionRoute",
    "DistributionRouter",
    "DistributionService",
    "FilesystemRegistryProvider",
    "FindingSeverity",
    "HmacSha256SignatureVerifier",
    "InstalledRegistryItem",
    "JsonRegistryInstallationStore",
    "LocalRegistryProvider",
    "MarketplaceKindDescriptor",
    "MarketplaceKindHandler",
    "MarketplaceKindHandlerRegistry",
    "MarketplaceKindRegistry",
    "PlatformRegistryValidationContextResolver",
    "PluginArtifactInstaller",
    "PluginRegistryArtifactInstaller",
    "PortabilityImportOwner",
    "REGISTRY_ACTIVATE_COMMAND",
    "REGISTRY_COLLECTION",
    "REGISTRY_ITEM_SCHEMA_VERSION",
    "REGISTRY_PIN_COMMAND",
    "REGISTRY_PREVIEW_COMMAND",
    "REGISTRY_UNPIN_COMMAND",
    "RegistryCommandHandlers",
    "RegistryDependency",
    "RegistryDiscoverySource",
    "RegistryInstallation",
    "RegistryInstallationSnapshot",
    "RegistryInstallationStore",
    "RegistryItem",
    "RegistryItemKind",
    "RegistryItemNotFoundError",
    "RegistryItemType",
    "RegistryManifestReference",
    "RegistryPluginReconciliationError",
    "RegistryProvider",
    "RegistryQuery",
    "RegistryResourceService",
    "RegistrySignatureVerifier",
    "RegistrySource",
    "RegistryUnavailableError",
    "RegistryValidationContextResolver",
    "TECHNICAL_CATEGORIES",
    "TECHNICAL_COST_STATUSES",
    "TECHNICAL_DEPLOYMENT_MODES",
    "TECHNICAL_EVALUATION_STATUSES",
    "TECHNICAL_LIFECYCLE_STATUSES",
    "TECHNICAL_NETWORK_STATUSES",
    "TechnicalMarketplaceMetadata",
    "TrustStatus",
    "ValidationContext",
    "ValidationFinding",
    "VersionRange",
    "builtin_marketplace_kind",
    "curate_discovered_candidate",
    "derive_technical_metadata",
    "has_errors",
    "is_technical_component",
    "load_hmac_signature_keys",
    "marketplace_kind_registry_with_builtins",
    "parse_registry_item_kind",
    "reconcile_registry_plugins",
    "register_distribution_control_plane",
    "registry_item_from_document",
    "registry_item_kind_value",
    "validate_item",
    "validate_registry_item_document",
]
