"""Release/provenance public API."""

from .adoption import (
    UPDATE_VALIDATION_EVIDENCE_SCHEMA_VERSION,
    UpdateGateEvidence,
    UpdateValidationEvidenceError,
    UpdateValidationEvidenceSet,
    load_update_validation_evidence,
    validate_update_adoption_evidence,
)
from .codec import ReleaseManifestError, load_release_manifest, release_manifest_from_dict
from .discovery import (
    COMPATIBILITY_INVENTORY_SCHEMA_VERSION,
    UPDATE_OBSERVATION_SCHEMA_VERSION,
    CompatibilityInventory,
    ObservedUpstream,
    UpdateCandidate,
    UpdateClassification,
    UpdateDiscoveryError,
    UpdateDiscoveryReport,
    UpdateDisposition,
    UpstreamInventoryEntry,
    evaluate_update_candidates,
    load_compatibility_inventory,
    load_observations,
    record_reviewed_candidate,
)
from .generator import (
    RELEASE_GENERATION_INPUT_SCHEMA_VERSION,
    ArtifactSource,
    DependencySetSource,
    ReleaseGenerationError,
    ReleaseGenerationInputs,
    generate_release_manifest,
    generate_release_manifest_from_file,
    load_release_generation_inputs,
    write_release_manifest,
)
from .models import (
    RELEASE_MANIFEST_SCHEMA_VERSION,
    CompatibilityRecord,
    CompatibilityStatus,
    DependencySetKind,
    DependencySetProvenance,
    GateStatus,
    ReleaseEvidence,
    ReleaseEvidenceKind,
    ReleaseGate,
    ReleaseKind,
    ReleaseManifest,
    ReleaseReadinessReport,
    UpstreamProvenance,
)
from .operator import ReleaseOperatorService
from .persistence import (
    DISCOVERY_REPORT_STATE_SCHEMA_VERSION,
    JsonDiscoveryReportStore,
    StoredDiscoveryReport,
)
from .providers import (
    GitDiscoveryResult,
    discover_git_heads,
    git_head_revision,
    write_git_discovery_result,
)
from .service import (
    COMMIT_BOUND_RELEASE_GATES,
    REQUIRED_RELEASE_GATES,
    evaluate_release,
    release_metadata,
)

__all__ = [
    "COMMIT_BOUND_RELEASE_GATES",
    "COMPATIBILITY_INVENTORY_SCHEMA_VERSION",
    "DISCOVERY_REPORT_STATE_SCHEMA_VERSION",
    "RELEASE_GENERATION_INPUT_SCHEMA_VERSION",
    "RELEASE_MANIFEST_SCHEMA_VERSION",
    "REQUIRED_RELEASE_GATES",
    "UPDATE_OBSERVATION_SCHEMA_VERSION",
    "UPDATE_VALIDATION_EVIDENCE_SCHEMA_VERSION",
    "ArtifactSource",
    "CompatibilityInventory",
    "CompatibilityRecord",
    "CompatibilityStatus",
    "DependencySetKind",
    "DependencySetProvenance",
    "DependencySetSource",
    "GateStatus",
    "GitDiscoveryResult",
    "JsonDiscoveryReportStore",
    "ObservedUpstream",
    "ReleaseEvidence",
    "ReleaseEvidenceKind",
    "ReleaseGate",
    "ReleaseGenerationError",
    "ReleaseGenerationInputs",
    "ReleaseKind",
    "ReleaseManifest",
    "ReleaseManifestError",
    "ReleaseOperatorService",
    "ReleaseReadinessReport",
    "StoredDiscoveryReport",
    "UpdateCandidate",
    "UpdateClassification",
    "UpdateDiscoveryError",
    "UpdateDiscoveryReport",
    "UpdateDisposition",
    "UpdateGateEvidence",
    "UpdateValidationEvidenceError",
    "UpdateValidationEvidenceSet",
    "UpstreamInventoryEntry",
    "UpstreamProvenance",
    "discover_git_heads",
    "evaluate_release",
    "evaluate_update_candidates",
    "generate_release_manifest",
    "generate_release_manifest_from_file",
    "git_head_revision",
    "load_compatibility_inventory",
    "load_observations",
    "load_release_generation_inputs",
    "load_release_manifest",
    "load_update_validation_evidence",
    "record_reviewed_candidate",
    "release_manifest_from_dict",
    "release_metadata",
    "validate_update_adoption_evidence",
    "write_git_discovery_result",
    "write_release_manifest",
]
