"""Governed feedback, learning-candidate and owner-domain promotion workflow (#595)."""

from .control_plane import (
    LEARNING_CANDIDATE_COLLECTION,
    LEARNING_COLLECTIONS,
    LEARNING_COMMANDS,
    LEARNING_FEEDBACK_COLLECTION,
    LearningCandidateResourceService,
    LearningFeedbackResourceService,
    register_learning_control_plane,
)
from .models import (
    LEARNING_SCHEMA_VERSION,
    FeedbackRecord,
    FeedbackType,
    LearningCandidate,
    LearningCandidateStatus,
    LearningGatePlan,
    LearningReference,
    LearningSourceType,
    LearningTarget,
    LearningTargetType,
    PromotionReceipt,
    candidate_from_dict,
    candidate_to_dict,
    feedback_from_dict,
    feedback_to_dict,
    new_feedback_id,
    new_learning_candidate_id,
)
from .promotion import (
    AgentPromotionAdapter,
    OwnerPromotionAdapter,
    PromotionRegistry,
    RoutingProfilePromotionAdapter,
    SkillPromotionAdapter,
)
from .repository import InMemoryLearningRepository, LearningRepository, SQLiteLearningRepository
from .service import LearningQualityGate, LearningService
from .sources import LearningSourceBridge

__all__ = [
    "LEARNING_CANDIDATE_COLLECTION",
    "LEARNING_COLLECTIONS",
    "LEARNING_COMMANDS",
    "LEARNING_FEEDBACK_COLLECTION",
    "LEARNING_SCHEMA_VERSION",
    "AgentPromotionAdapter",
    "FeedbackRecord",
    "FeedbackType",
    "InMemoryLearningRepository",
    "LearningCandidate",
    "LearningCandidateResourceService",
    "LearningCandidateStatus",
    "LearningFeedbackResourceService",
    "LearningGatePlan",
    "LearningQualityGate",
    "LearningReference",
    "LearningRepository",
    "LearningService",
    "LearningSourceBridge",
    "LearningSourceType",
    "LearningTarget",
    "LearningTargetType",
    "OwnerPromotionAdapter",
    "PromotionReceipt",
    "PromotionRegistry",
    "RoutingProfilePromotionAdapter",
    "SQLiteLearningRepository",
    "SkillPromotionAdapter",
    "candidate_from_dict",
    "candidate_to_dict",
    "feedback_from_dict",
    "feedback_to_dict",
    "new_feedback_id",
    "new_learning_candidate_id",
    "register_learning_control_plane",
]
