"""First-run onboarding composition for the general-purpose platform."""

from .agent_lifecycle import (
    FIRST_RUN_AGENT_EXECUTION_PROFILE,
    FIRST_RUN_AGENT_ID_KEY,
    FIRST_RUN_EXECUTION_PROFILE_KEY,
    FIRST_RUN_WORKSPACE_ID_KEY,
    FirstRunAgentLifecycleBackend,
)
from .component_setup import (
    COMPONENT_SETUP_RESOURCE_ID,
    ONBOARDING_SAVE_COMPONENT_PROFILE_COMMAND,
    ONBOARDING_SELECT_COMPONENT_PROFILE_COMMAND,
    ComponentDiscoverySource,
    OnboardingComponentSetupService,
)
from .components import (
    SETUP_PROFILE_SCHEMA_VERSION,
    CompatibilityEnvironment,
    CompatibilityResult,
    CompatibilityState,
    ComponentAvailability,
    ComponentCategory,
    ComponentCompatibilityResolver,
    ComponentLifecycle,
    ComponentRequirement,
    ComponentSelectionLayer,
    DiscoveredComponent,
    JsonSetupProfileStore,
    OverrideScope,
    RequirementKind,
    SetupMode,
    SetupProfile,
    SetupProfileState,
    recommend_setup_profile,
    resolve_component_selection,
)
from .control_plane import (
    COMPONENT_SETUP_COLLECTION,
    SETUP_SESSION_COLLECTION,
    ComponentSetupResourceService,
    OnboardingResourceService,
    SetupSessionResourceService,
    register_component_setup_control_plane,
    register_onboarding_control_plane,
    register_setup_lifecycle_control_plane,
)
from .first_run_service import (
    FIRST_RUN_RESOURCE_ID,
    ONBOARDING_COLLECTION,
    ONBOARDING_COMMANDS,
    ONBOARDING_CONFIGURE_MODEL_COMMAND,
    OnboardingService,
)
from .first_task import ONBOARDING_RUN_FIRST_TASK_COMMAND, FirstRunTaskService
from .persistence import (
    ONBOARDING_PROVIDER_SCHEMA_VERSION,
    JsonModelProviderSetupStore,
    JsonOnboardingCommandStore,
    ModelProviderSetupRecord,
    OnboardingCommandRecord,
)
from .providers import OnboardingModelAdapter, OnboardingModelEndpoint
from .runtime_discovery import SingleNodeComponentDiscoverySource
from .setup_lifecycle import (
    ONBOARDING_PROVISION_SETUP_COMMAND,
    ONBOARDING_UPDATE_SETUP_SESSION_COMMAND,
    ONBOARDING_VALIDATE_SETUP_COMMAND,
    SETUP_SESSION_RESOURCE_ID,
    BrowserFirstSetupService,
    JsonSetupSessionStore,
    ProvisioningActionKind,
    ProvisioningActionState,
    RegistrySelection,
    SetupStep,
    SetupStepState,
)

__all__ = [
    "BrowserFirstSetupService",
    "COMPONENT_SETUP_COLLECTION",
    "COMPONENT_SETUP_RESOURCE_ID",
    "FIRST_RUN_AGENT_EXECUTION_PROFILE",
    "FIRST_RUN_AGENT_ID_KEY",
    "FIRST_RUN_EXECUTION_PROFILE_KEY",
    "FIRST_RUN_RESOURCE_ID",
    "FIRST_RUN_WORKSPACE_ID_KEY",
    "JsonSetupSessionStore",
    "ONBOARDING_COLLECTION",
    "ONBOARDING_COMMANDS",
    "ONBOARDING_CONFIGURE_MODEL_COMMAND",
    "ONBOARDING_PROVIDER_SCHEMA_VERSION",
    "ONBOARDING_PROVISION_SETUP_COMMAND",
    "ONBOARDING_RUN_FIRST_TASK_COMMAND",
    "ONBOARDING_SAVE_COMPONENT_PROFILE_COMMAND",
    "ONBOARDING_SELECT_COMPONENT_PROFILE_COMMAND",
    "ONBOARDING_UPDATE_SETUP_SESSION_COMMAND",
    "ONBOARDING_VALIDATE_SETUP_COMMAND",
    "ProvisioningActionKind",
    "ProvisioningActionState",
    "RegistrySelection",
    "SETUP_PROFILE_SCHEMA_VERSION",
    "SETUP_SESSION_COLLECTION",
    "SETUP_SESSION_RESOURCE_ID",
    "CompatibilityEnvironment",
    "CompatibilityResult",
    "CompatibilityState",
    "ComponentAvailability",
    "ComponentCategory",
    "ComponentCompatibilityResolver",
    "ComponentDiscoverySource",
    "ComponentLifecycle",
    "ComponentRequirement",
    "ComponentSelectionLayer",
    "ComponentSetupResourceService",
    "DiscoveredComponent",
    "FirstRunAgentLifecycleBackend",
    "FirstRunTaskService",
    "JsonModelProviderSetupStore",
    "JsonOnboardingCommandStore",
    "JsonSetupProfileStore",
    "ModelProviderSetupRecord",
    "OnboardingCommandRecord",
    "OnboardingComponentSetupService",
    "OnboardingModelAdapter",
    "OnboardingModelEndpoint",
    "OnboardingResourceService",
    "OnboardingService",
    "OverrideScope",
    "RequirementKind",
    "SetupMode",
    "SetupProfile",
    "SetupProfileState",
    "SetupSessionResourceService",
    "SetupStep",
    "SetupStepState",
    "SingleNodeComponentDiscoverySource",
    "recommend_setup_profile",
    "register_component_setup_control_plane",
    "register_onboarding_control_plane",
    "register_setup_lifecycle_control_plane",
    "resolve_component_selection",
]
