"""First-run onboarding composition for the general-purpose platform."""

from .agent_lifecycle import (
    FIRST_RUN_AGENT_EXECUTION_PROFILE,
    FIRST_RUN_AGENT_ID_KEY,
    FIRST_RUN_EXECUTION_PROFILE_KEY,
    FIRST_RUN_WORKSPACE_ID_KEY,
    FirstRunAgentLifecycleBackend,
)
from .components import (
    SETUP_PROFILE_SCHEMA_VERSION,
    CompatibilityEnvironment,
    CompatibilityResult,
    CompatibilityState,
    ComponentAvailability,
    ComponentCategory,
    ComponentCompatibilityResolver,
    ComponentLifecycle,
    ComponentRequirement,
    ComponentSelectionLayer,
    DiscoveredComponent,
    JsonSetupProfileStore,
    OverrideScope,
    RequirementKind,
    SetupMode,
    SetupProfile,
    SetupProfileState,
    recommend_setup_profile,
    resolve_component_selection,
)
from .control_plane import OnboardingResourceService, register_onboarding_control_plane
from .first_task import ONBOARDING_RUN_FIRST_TASK_COMMAND, FirstRunTaskService
from .persistence import (
    ONBOARDING_PROVIDER_SCHEMA_VERSION,
    JsonModelProviderSetupStore,
    JsonOnboardingCommandStore,
    ModelProviderSetupRecord,
    OnboardingCommandRecord,
)
from .providers import OnboardingModelAdapter, OnboardingModelEndpoint
from .service import (
    FIRST_RUN_RESOURCE_ID,
    ONBOARDING_COLLECTION,
    ONBOARDING_COMMANDS,
    ONBOARDING_CONFIGURE_MODEL_COMMAND,
    OnboardingService,
)

__all__ = [
    "FIRST_RUN_AGENT_EXECUTION_PROFILE",
    "FIRST_RUN_AGENT_ID_KEY",
    "FIRST_RUN_EXECUTION_PROFILE_KEY",
    "FIRST_RUN_RESOURCE_ID",
    "FIRST_RUN_WORKSPACE_ID_KEY",
    "ONBOARDING_COLLECTION",
    "ONBOARDING_COMMANDS",
    "ONBOARDING_CONFIGURE_MODEL_COMMAND",
    "ONBOARDING_PROVIDER_SCHEMA_VERSION",
    "ONBOARDING_RUN_FIRST_TASK_COMMAND",
    "SETUP_PROFILE_SCHEMA_VERSION",
    "CompatibilityEnvironment",
    "CompatibilityResult",
    "CompatibilityState",
    "ComponentAvailability",
    "ComponentCategory",
    "ComponentCompatibilityResolver",
    "ComponentLifecycle",
    "ComponentRequirement",
    "ComponentSelectionLayer",
    "DiscoveredComponent",
    "FirstRunAgentLifecycleBackend",
    "FirstRunTaskService",
    "JsonModelProviderSetupStore",
    "JsonOnboardingCommandStore",
    "JsonSetupProfileStore",
    "ModelProviderSetupRecord",
    "OnboardingCommandRecord",
    "OnboardingModelAdapter",
    "OnboardingModelEndpoint",
    "OnboardingResourceService",
    "OnboardingService",
    "OverrideScope",
    "RequirementKind",
    "SetupMode",
    "SetupProfile",
    "SetupProfileState",
    "recommend_setup_profile",
    "register_onboarding_control_plane",
    "resolve_component_selection",
]
