from __future__ import annotations

import asyncio

from ai_multi_agent_platform.automation import (
    AutomationService,
    AutomationState,
    IdentityContext,
    InMemoryAutomationRepository,
    TaskTemplate,
    TriggerDefinition,
    TriggerType,
)
from ai_multi_agent_platform.contracts.types import AuthorizationDecision, AuthorizationRequest
from ai_multi_agent_platform.control_plane import ControlPlane, ControlPlaneHTTP, HTTPRequest
from ai_multi_agent_platform.domain import new_id
from ai_multi_agent_platform.kernel import InMemoryKernelRepository, PlatformKernel
from ai_multi_agent_platform.testing import (
    FakeAuthorizationProvider,
    FakeLifecycleBackend,
    FakeOrchestrator,
)


class AutomationSearchAuthorization(FakeAuthorizationProvider):
    def __init__(self, denied_project_id: str | None = None) -> None:
        super().__init__()
        self.denied_project_id = denied_project_id

    async def authorize(self, request: AuthorizationRequest) -> AuthorizationDecision:
        self.calls.append(request)
        if (
            self.denied_project_id is not None
            and request.action in {"automation:list", "automation-delivery:list"}
            and request.context.project_id == self.denied_project_id
        ):
            return AuthorizationDecision(allowed=False, reason="automation-project-hidden")
        return AuthorizationDecision(allowed=True, reason="automation-search-visible")


async def _stack(
    authorization: FakeAuthorizationProvider | None = None,
) -> tuple[ControlPlane, ControlPlaneHTTP, AutomationService]:
    async def create_task(*args: object) -> str:
        return new_id("task")

    automation_service = AutomationService(
        repository=InMemoryAutomationRepository(),
        task_creator=create_task,
    )
    repository = InMemoryKernelRepository()
    kernel = PlatformKernel(
        orchestrator=FakeOrchestrator(),
        lifecycle=FakeLifecycleBackend(),
        repository=repository,
    )
    control_plane = ControlPlane(
        kernel=kernel,
        events=repository,
        authorization=authorization,
        automation_service=automation_service,
    )
    return control_plane, ControlPlaneHTTP(control_plane), automation_service


async def _seed_automation(
    service: AutomationService,
    *,
    project_id: str,
    owner_id: str,
    name: str,
    occurrence_id: str,
) -> tuple[str, str]:
    automation = await service.create_automation(
        name=name,
        description=f"Searchable automation for {name}",
        identity=IdentityContext(
            principal_ref=f"user:{owner_id}",
            owner_type="user",
            owner_id=owner_id,
        ),
        trigger=TriggerDefinition(type=TriggerType.MANUAL),
        task_template=TaskTemplate(
            title=f"Generated by {name}",
            objective=f"Exercise automation search for {name}",
            project_id=project_id,
        ),
        project_id=project_id,
    )
    delivery = await service.test_trigger(automation.id, occurrence_id=occurrence_id)
    return automation.id, delivery.id


async def _search(http: ControlPlaneHTTP, **query: str) -> dict[str, object]:
    response = await http.handle(HTTPRequest(method="GET", path="/api/v1/search", query=query))
    assert response.status == 200
    assert isinstance(response.body, dict)
    return response.body


def _items(page: dict[str, object]) -> list[dict[str, object]]:
    raw_items = page["items"]
    assert isinstance(raw_items, list)
    assert all(isinstance(item, dict) for item in raw_items)
    return raw_items


def test_automation_and_delivery_use_registered_global_search() -> None:
    async def scenario() -> None:
        control_plane, http, service = await _stack()
        project_id = new_id("project")
        automation_id, delivery_id = await _seed_automation(
            service,
            project_id=project_id,
            owner_id="automation-owner",
            name="Nightly Search Audit",
            occurrence_id="nightly-search-audit",
        )
        await service.set_state(automation_id, AutomationState.PAUSED)

        automation_page = await _search(http, id=automation_id, type="automation")
        assert automation_page["total"] == 1
        automation = _items(automation_page)[0]
        assert automation["resource_type"] == "automation"
        assert automation["resource_id"] == automation_id
        assert automation["title"] == "Nightly Search Audit"
        assert automation["summary"] == "Searchable automation for Nightly Search Audit"
        assert automation["project_id"] == project_id
        assert automation["owner_type"] == "user"
        assert automation["owner_id"] == "automation-owner"
        assert automation["status"] == "paused"
        assert automation["version"] == "2"
        assert automation["canonical_ref"] == f"/api/v1/automations/{automation_id}"
        assert automation["provenance"] == {
            "indexed_from": "canonical-control-plane",
            "collection": "automations",
        }

        paused = await _search(http, type="automation", status="paused")
        assert paused["total"] == 1
        by_project = await _search(http, type="automation", project_id=project_id)
        assert by_project["total"] == 1

        delivery_page = await _search(http, id=delivery_id, type="automation-delivery")
        assert delivery_page["total"] == 1
        delivery = _items(delivery_page)[0]
        assert delivery["resource_type"] == "automation-delivery"
        assert delivery["resource_id"] == delivery_id
        assert delivery["project_id"] == project_id
        assert delivery["owner_type"] == "user"
        assert delivery["owner_id"] == "automation-owner"
        assert delivery["status"] == "succeeded"
        assert delivery["canonical_ref"] == f"/api/v1/automation-deliveries/{delivery_id}"

        by_automation = await _search(http, q=automation_id, type="automation-delivery")
        assert by_automation["total"] == 1
        by_source = await _search(http, q="manual-test", type="automation-delivery")
        assert by_source["total"] == 1
        by_trigger = await _search(http, q="manual", type="automation-delivery")
        assert by_trigger["total"] == 1
        succeeded = await _search(http, type="automation-delivery", status="succeeded")
        assert succeeded["total"] == 1

        rebuilt = await control_plane.rebuild_search_index()
        assert rebuilt == 2

    asyncio.run(scenario())


def test_automation_search_hides_cross_project_items_counts_and_relationships() -> None:
    async def scenario() -> None:
        visible_project = new_id("project")
        hidden_project = new_id("project")
        authorization = AutomationSearchAuthorization(denied_project_id=hidden_project)
        _, http, service = await _stack(authorization)

        visible_automation, visible_delivery = await _seed_automation(
            service,
            project_id=visible_project,
            owner_id="visible-automation-owner",
            name="Visible Automation",
            occurrence_id="visible-delivery",
        )
        hidden_automation, hidden_delivery = await _seed_automation(
            service,
            project_id=hidden_project,
            owner_id="hidden-automation-owner",
            name="Hidden Automation Secret",
            occurrence_id="hidden-delivery",
        )

        page = await _search(http, type="automation,automation-delivery")
        assert page["total"] == 2
        visible_ids = {item["resource_id"] for item in _items(page)}
        assert visible_ids == {visible_automation, visible_delivery}
        serialized = repr(page)
        assert hidden_automation not in serialized
        assert hidden_delivery not in serialized
        assert hidden_project not in serialized
        assert "Hidden Automation Secret" not in serialized
        assert "hidden-automation-owner" not in serialized

        hidden_exact = await _search(http, id=hidden_automation, type="automation")
        assert hidden_exact["total"] == 0
        assert hidden_automation not in repr(hidden_exact)

        hidden_delivery_exact = await _search(
            http,
            id=hidden_delivery,
            type="automation-delivery",
        )
        assert hidden_delivery_exact["total"] == 0
        assert hidden_delivery not in repr(hidden_delivery_exact)

        hidden_name = await _search(http, q="Hidden Automation Secret", type="automation")
        assert hidden_name["total"] == 0
        hidden_relationship = await _search(
            http,
            q=hidden_automation,
            type="automation-delivery",
        )
        assert hidden_relationship["total"] == 0

        visible_exact = await _search(http, id=visible_automation, type="automation")
        assert visible_exact["total"] == 1

        assert any(call.action == "automation:list" for call in authorization.calls)
        assert any(call.action == "automation-delivery:list" for call in authorization.calls)

    asyncio.run(scenario())
