"""Canonical managed Application definitions, lifecycle and runtime contracts."""

from .control_plane import (
    APPLICATION_COLLECTION,
    APPLICATION_COLLECTIONS,
    APPLICATION_COMMANDS,
    APPLICATION_INSTANCE_COLLECTION,
    APPLICATION_MODULE,
    ApplicationInstanceResourceService,
    ApplicationResourceService,
    application_control_plane_module,
    register_application_control_plane,
)
from .definition import Application
from .local_process_runtime import LocalProcessApplicationRuntime
from .manifest import (
    APPLICATION_MANIFEST_SCHEMA,
    application_manifest_from_document,
    validate_application_manifest_document,
)
from .models import (
    APPLICATION_MANIFEST_SCHEMA_VERSION,
    ApplicationConfigurationField,
    ApplicationConfigValueType,
    ApplicationDesiredState,
    ApplicationEndpoint,
    ApplicationEndpointExposure,
    ApplicationEndpointProtocol,
    ApplicationEndpointResolution,
    ApplicationHealthCheck,
    ApplicationHealthCheckKind,
    ApplicationHealthStatus,
    ApplicationInstallRequest,
    ApplicationInstance,
    ApplicationLogEntry,
    ApplicationManifest,
    ApplicationMaturity,
    ApplicationObservedState,
    ApplicationResourceAssociation,
    ApplicationResourceRequirements,
    ApplicationSecretField,
    ApplicationService,
    ApplicationServiceRuntime,
    ApplicationServiceState,
    ApplicationUi,
    ApplicationUiOpenMode,
    ApplicationVolume,
    ApplicationVolumeBinding,
    ApplicationVolumeKind,
    ApplicationVolumeMount,
)
from .repository import ApplicationRepository, InMemoryApplicationRepository
from .runtime import (
    ApplicationInstanceNotFoundError,
    ApplicationPreparationError,
    ApplicationRuntime,
    ApplicationRuntimeDescriptor,
    ApplicationRuntimeError,
    ApplicationRuntimeUnavailableError,
)
from .service import (
    ApplicationLifecycleService,
    ApplicationRecoveryFailure,
    ApplicationRecoveryReport,
    ApplicationRuntimeRegistry,
)
from .sqlite_repository import SqliteApplicationRepository
from .workspace_execution import LocalApplicationWorkspaceBinder

__all__ = [
    "APPLICATION_COLLECTION",
    "APPLICATION_COLLECTIONS",
    "APPLICATION_COMMANDS",
    "APPLICATION_INSTANCE_COLLECTION",
    "APPLICATION_MANIFEST_SCHEMA",
    "APPLICATION_MANIFEST_SCHEMA_VERSION",
    "APPLICATION_MODULE",
    "Application",
    "ApplicationConfigValueType",
    "ApplicationConfigurationField",
    "ApplicationDesiredState",
    "ApplicationEndpoint",
    "ApplicationEndpointExposure",
    "ApplicationEndpointProtocol",
    "ApplicationEndpointResolution",
    "ApplicationHealthCheck",
    "ApplicationHealthCheckKind",
    "ApplicationHealthStatus",
    "ApplicationInstallRequest",
    "ApplicationInstance",
    "ApplicationInstanceNotFoundError",
    "ApplicationInstanceResourceService",
    "ApplicationLifecycleService",
    "ApplicationLogEntry",
    "ApplicationManifest",
    "ApplicationMaturity",
    "ApplicationObservedState",
    "ApplicationPreparationError",
    "ApplicationRecoveryFailure",
    "ApplicationRecoveryReport",
    "ApplicationRepository",
    "ApplicationResourceAssociation",
    "ApplicationResourceRequirements",
    "ApplicationResourceService",
    "ApplicationRuntime",
    "ApplicationRuntimeDescriptor",
    "ApplicationRuntimeError",
    "ApplicationRuntimeRegistry",
    "ApplicationRuntimeUnavailableError",
    "ApplicationSecretField",
    "ApplicationService",
    "ApplicationServiceRuntime",
    "ApplicationServiceState",
    "ApplicationUi",
    "ApplicationUiOpenMode",
    "ApplicationVolume",
    "ApplicationVolumeBinding",
    "ApplicationVolumeKind",
    "ApplicationVolumeMount",
    "InMemoryApplicationRepository",
    "LocalApplicationWorkspaceBinder",
    "LocalProcessApplicationRuntime",
    "SqliteApplicationRepository",
    "application_control_plane_module",
    "application_manifest_from_document",
    "register_application_control_plane",
    "validate_application_manifest_document",
]
