"""Canonical distributed node, worker and scheduling primitives."""

from .capability_provider import DISTRIBUTED_ECHO_TOOL_REF, DistributedExecutorEchoProvider
from .control_plane import (
    DISTRIBUTED_ADMIN_COMMANDS,
    NODE_COLLECTION,
    WORKER_COLLECTION,
    WORKER_JOB_COLLECTION,
    DistributedAdminCommandHandlers,
    NodeResourceService,
    WorkerJobResourceService,
    WorkerResourceService,
    register_distributed_control_plane,
)
from .disaster_recovery import prepare_registry_disaster_recovery
from .executor_worker import (
    EXECUTOR_WORKER_INPUT_KEY,
    EXECUTOR_WORKER_INPUT_SCHEMA,
    ExecutorWorker,
    ExecutorWorkspaceResolver,
    executor_worker_input,
)
from .failover import (
    FailoverError,
    FailoverFenceReceipt,
    FailoverRejectionCode,
    WorkerOwnershipFencer,
)
from .lifecycle import DistributedLifecycleBackend
from .models import (
    WORKER_PROTOCOL_VERSION,
    AcceleratorResource,
    CandidateEvaluation,
    Heartbeat,
    JobRequirements,
    JobResultStatus,
    NodeRecord,
    NodeStatus,
    RegistrationRequest,
    RejectionCode,
    RejectionReason,
    Reservation,
    ReservationStatus,
    ResourceSnapshot,
    SchedulingDecision,
    WorkerJobRequest,
    WorkerJobResult,
    WorkerRecord,
    WorkerStatus,
)
from .persistence import (
    DISTRIBUTED_STATE_SCHEMA_VERSION,
    DistributedStateStore,
    JsonDistributedStateStore,
)
from .providers import DistributedNodeProvider, DistributedWorkerProvider
from .registry import DistributedRegistry, RegistryError, RegistrySnapshot
from .runtime import DispatchRecord, DispatchState, DistributedRuntime
from .scheduler import DeterministicScheduler, NoEligibleWorkerError, ScheduledPlacement
from .telemetry import DistributedTelemetry
from .transport import (
    WORKER_COMMAND_TOPIC_PREFIX,
    WORKER_REPLY_TOPIC_PREFIX,
    WORKER_TRANSPORT_SCHEMA_VERSION,
    RemoteWorkerTransportError,
    TransportWorkerDispatcher,
    WorkerResultProvider,
    WorkerTransportCodec,
    WorkerTransportEndpoint,
    worker_command_topic,
)
from .worker import LocalWorker, WorkerDispatcher
from .worker_protocol import (
    WorkerHeartbeatRequest,
    WorkerProtocolAuthorizationError,
    WorkerProtocolError,
    WorkerProtocolReceipt,
    WorkerProtocolService,
    WorkerRequestAuthenticator,
    WorkerRequestCredentials,
)
from .workspace import (
    MaterializingWorkerDispatcher,
    WorkerWorkspaceResolver,
    WorkspaceDispatchEvidence,
    WorkspaceJobMaterializationResolver,
)

__all__ = [
    "DISTRIBUTED_ADMIN_COMMANDS",
    "DISTRIBUTED_ECHO_TOOL_REF",
    "DISTRIBUTED_STATE_SCHEMA_VERSION",
    "EXECUTOR_WORKER_INPUT_KEY",
    "EXECUTOR_WORKER_INPUT_SCHEMA",
    "NODE_COLLECTION",
    "WORKER_COLLECTION",
    "WORKER_JOB_COLLECTION",
    "WORKER_COMMAND_TOPIC_PREFIX",
    "WORKER_PROTOCOL_VERSION",
    "WORKER_REPLY_TOPIC_PREFIX",
    "WORKER_TRANSPORT_SCHEMA_VERSION",
    "AcceleratorResource",
    "CandidateEvaluation",
    "DeterministicScheduler",
    "DispatchRecord",
    "DispatchState",
    "DistributedAdminCommandHandlers",
    "DistributedExecutorEchoProvider",
    "DistributedLifecycleBackend",
    "DistributedNodeProvider",
    "DistributedRegistry",
    "DistributedRuntime",
    "DistributedStateStore",
    "DistributedTelemetry",
    "DistributedWorkerProvider",
    "ExecutorWorker",
    "ExecutorWorkspaceResolver",
    "FailoverError",
    "FailoverFenceReceipt",
    "FailoverRejectionCode",
    "Heartbeat",
    "JobRequirements",
    "JobResultStatus",
    "JsonDistributedStateStore",
    "LocalWorker",
    "MaterializingWorkerDispatcher",
    "NoEligibleWorkerError",
    "NodeRecord",
    "NodeResourceService",
    "NodeStatus",
    "RegistrationRequest",
    "RegistryError",
    "RegistrySnapshot",
    "RejectionCode",
    "RejectionReason",
    "RemoteWorkerTransportError",
    "Reservation",
    "ReservationStatus",
    "ResourceSnapshot",
    "ScheduledPlacement",
    "SchedulingDecision",
    "TransportWorkerDispatcher",
    "WorkerDispatcher",
    "WorkerHeartbeatRequest",
    "WorkerJobRequest",
    "WorkerJobResourceService",
    "WorkerJobResult",
    "WorkerOwnershipFencer",
    "WorkerProtocolAuthorizationError",
    "WorkerProtocolError",
    "WorkerProtocolReceipt",
    "WorkerProtocolService",
    "WorkerRecord",
    "WorkerRequestAuthenticator",
    "WorkerRequestCredentials",
    "WorkerResourceService",
    "WorkerResultProvider",
    "WorkerStatus",
    "WorkerTransportCodec",
    "WorkerTransportEndpoint",
    "WorkerWorkspaceResolver",
    "WorkspaceDispatchEvidence",
    "WorkspaceJobMaterializationResolver",
    "executor_worker_input",
    "prepare_registry_disaster_recovery",
    "register_distributed_control_plane",
    "worker_command_topic",
]
