"""Canonical distributed node, worker and scheduling primitives."""

from .control_plane import (
    DISTRIBUTED_ADMIN_COMMANDS,
    NODE_COLLECTION,
    WORKER_COLLECTION,
    WORKER_JOB_COLLECTION,
    DistributedAdminCommandHandlers,
    NodeResourceService,
    WorkerJobResourceService,
    WorkerResourceService,
    register_distributed_control_plane,
)
from .disaster_recovery import prepare_registry_disaster_recovery
from .models import (
    WORKER_PROTOCOL_VERSION,
    AcceleratorResource,
    CandidateEvaluation,
    Heartbeat,
    JobRequirements,
    JobResultStatus,
    NodeRecord,
    NodeStatus,
    RegistrationRequest,
    RejectionCode,
    RejectionReason,
    Reservation,
    ReservationStatus,
    ResourceSnapshot,
    SchedulingDecision,
    WorkerJobRequest,
    WorkerJobResult,
    WorkerRecord,
    WorkerStatus,
)
from .persistence import (
    DISTRIBUTED_STATE_SCHEMA_VERSION,
    DistributedStateStore,
    JsonDistributedStateStore,
)
from .providers import DistributedNodeProvider, DistributedWorkerProvider
from .registry import DistributedRegistry, RegistryError, RegistrySnapshot
from .runtime import DispatchRecord, DispatchState, DistributedRuntime
from .scheduler import DeterministicScheduler, NoEligibleWorkerError, ScheduledPlacement
from .telemetry import DistributedTelemetry
from .worker import LocalWorker, WorkerDispatcher
from .worker_protocol import (
    WorkerHeartbeatRequest,
    WorkerProtocolAuthorizationError,
    WorkerProtocolError,
    WorkerProtocolReceipt,
    WorkerProtocolService,
    WorkerRequestAuthenticator,
    WorkerRequestCredentials,
)
from .workspace import (
    MaterializingWorkerDispatcher,
    WorkerWorkspaceResolver,
    WorkspaceDispatchEvidence,
    WorkspaceJobMaterializationResolver,
)

__all__ = [
    "DISTRIBUTED_ADMIN_COMMANDS",
    "DISTRIBUTED_STATE_SCHEMA_VERSION",
    "NODE_COLLECTION",
    "WORKER_COLLECTION",
    "WORKER_JOB_COLLECTION",
    "WORKER_PROTOCOL_VERSION",
    "AcceleratorResource",
    "CandidateEvaluation",
    "DeterministicScheduler",
    "DispatchRecord",
    "DispatchState",
    "DistributedAdminCommandHandlers",
    "DistributedNodeProvider",
    "DistributedRegistry",
    "DistributedRuntime",
    "DistributedStateStore",
    "DistributedTelemetry",
    "DistributedWorkerProvider",
    "Heartbeat",
    "JobRequirements",
    "JobResultStatus",
    "JsonDistributedStateStore",
    "LocalWorker",
    "MaterializingWorkerDispatcher",
    "NoEligibleWorkerError",
    "NodeRecord",
    "NodeResourceService",
    "NodeStatus",
    "RegistrationRequest",
    "RegistryError",
    "RegistrySnapshot",
    "RejectionCode",
    "RejectionReason",
    "Reservation",
    "ReservationStatus",
    "ResourceSnapshot",
    "ScheduledPlacement",
    "SchedulingDecision",
    "WorkerDispatcher",
    "WorkerHeartbeatRequest",
    "WorkerJobRequest",
    "WorkerJobResourceService",
    "WorkerJobResult",
    "WorkerProtocolAuthorizationError",
    "WorkerProtocolError",
    "WorkerProtocolReceipt",
    "WorkerProtocolService",
    "WorkerRecord",
    "WorkerRequestAuthenticator",
    "WorkerRequestCredentials",
    "WorkerResourceService",
    "WorkerStatus",
    "WorkerWorkspaceResolver",
    "WorkspaceDispatchEvidence",
    "WorkspaceJobMaterializationResolver",
    "prepare_registry_disaster_recovery",
    "register_distributed_control_plane",
]
