from run_error_cases import (
    test_all_current_contract_error_codes_have_intentional_http_mapping as test_all_current_contract_error_codes_have_intentional_http_mapping,
    test_generated_openapi_documents_run_error_contract as test_generated_openapi_documents_run_error_contract,
)
